import mysql.connector as c
con=c.connect(host="localhost",user="root",password="",database="socialmedia")
if con.is_connected() :
    mycursor=con.cursor()
    mycursor.execute("CREATE TABLE user(username varchar(30) PRIMARY KEY,first_name varchar(30),middle_name varchar(30),last_name varchar(30),mobile varchar(15),email varchar(30),password varchar(30) NOT NULL)")
    mycursor.execute("CREATE TABLE friend(username varchar(30),friend varchar(30),PRIMARY KEY(username,friend),FOREIGN KEY (username) REFERENCES user(username),FOREIGN KEY (friend) REFERENCES user(username))")
    mycursor.execute("CREATE TABLE followers(username varchar(30),followed_by varchar(30),PRIMARY KEY(username,followed_by),FOREIGN KEY (username) REFERENCES user(username),FOREIGN KEY (followed_by) REFERENCES user(username))")
    mycursor.execute("CREATE TABLE message(msg_id int PRIMARY KEY,sender varchar(30) NOT NULL,receiver varchar(30) NOT NULL,msg_body text NOT NULL,time datetime NOT NULL,FOREIGN KEY (sender) REFERENCES user(username),FOREIGN KEY (receiver) REFERENCES user(username))")
    mycursor.execute("CREATE TABLE post(post_id int PRIMARY KEY,username varchar(30) NOT NULL,caption text,date date NOT NULL,friend varchar(30),FOREIGN KEY (username) REFERENCES user(username))")
    mycursor.execute("CREATE TABLE comments(comment_id int PRIMARY KEY,post_id int NOT NULL,username varchar(30) NOT NULL,comment_body text NOT NULL,FOREIGN KEY (post_id) REFERENCES post(post_id),FOREIGN KEY (username) REFERENCES user(username))")
    mycursor.execute("INSERT INTO user VALUES('aryangoyal','Aryan',NULL,'Goyal','3086242456','aryan.goyal.ug21@nsut.ac.in','abcdefg'),('batman','Christian',NULL,'Bale','9992213456','christian__bale@gmail.com','batmobile'),('harry_potter','Harry','James','Potter','7878782359','thechosenone@yahoo.com','ukwho'),('london2022','London',NULL,'Downey','2987928759','london_downey@yahoo.com','387777'),('paulatreides','Paul',NULL,'Atreides','2785827298','paulatreides55@gmail.com','admin420'),('realduncan','Duncan','Paul','Idahoe','4666437782','paul-idahoe@hotmail.com','password'),('tyler_p','Tyler','William','Pattinson','8275827581','tylerpattinson@gmail.com','8358783'),('_chaitanya.03','Chaitanya',NULL,'Bhargava','9717393877','chaitanyabhargava5@gmail.com','12345')")
    mycursor.execute("INSERT INTO friend VALUES('aryangoyal','_chaitanya.03'),('batman','_chaitanya.03'),('harry_potter','_chaitanya.03'),('paulatreides','realduncan'),('paulatreides','_chaitanya.03'),('realduncan','paulatreides'),('_chaitanya.03','aryangoyal'),('_chaitanya.03','batman'),('_chaitanya.03','harry_potter'),('_chaitanya.03','paulatreides')")
    mycursor.execute("INSERT INTO followers VALUES('aryangoyal','_chaitanya.03'),('batman','aryangoyal'),('batman','_chaitanya.03'),('harry_potter','tyler_p'),('harry_potter','_chaitanya.03'),('london2022','tyler_p'),('paulatreides','realduncan'),('paulatreides','_chaitanya.03'),('_chaitanya.03','aryangoyal')")
    mycursor.execute("INSERT INTO message VALUES(1,'_chaitanya,03','tyler_p','this is a test message','2022-10-11 09:27:39'),(2,'_chaitanya.03','aryangoyal','Hello, how are you doing?','2022-09-05 15:24:22'),(3,'harry_potter','_chaitanya.03','See you tomorrow!','2022-09-08 15:20:41'),(4,'realduncan','paulatreides','Talk to you later.','2022-07-19 22:17:29'),(5,'paulatreides','realduncan','Good night!','2021-07-15 14:07:37'),(6,'london2022','harry_potter','Bye bye!','2022-11-08 09:48:03'),(7,'batman','aryangoyal','this is me batman','2022-03-09 01:19:22'),(8,'aryangoyal','_chaitanya.03','Hello can you send me the work for today?','2022-08-16 14:20:28')")
    mycursor.execute("INSERT INTO post VALUES(1,'_chaitanya.03','My first post on here','2022-11-02'),(2,'aryangoyal','Went to Shimla on a trip.','2022-11-01'),(3,'batman','Shooting the next installment in the batman franchise','2022-09-22'),(4,'paulatreides','My friends and I are going swimming','2022-07-12'),(5,'tyler_p','Happy New Year','2022-01-01'),(6,'london2022','Awesome cafe at Hudson Lane!','2022-02-11'),(7,'realduncan','Bought a new Mercedes','2022-11-01'),(8,'_chaitanya.03','New song I recorded on the guitar! Give it a listen.','2022-04-20')")
    mycursor.execute("INSERT INTO comments VALUES(1,1,'aryangoyal','Welcome!'),(2,3,'tyler_p','Cannot wait to watch!'),(3,8,'london2022','Well played!'),(4,5,'realduncan','Happy New Year!'),(5,7,'aryangoyal','Nice car man!'),(6,6,'_chaitanya.03','Yes I love their food and ambience'),(7,2,'paulatreides','How was the weather there?'),(8,5,'london2022','Have a great 2022!')")
    con.commit()
else:
    print("Not connected")